---
- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add the NodeSource deb repository
  apt_repository:
    repo: '{{ item }} https://deb.nodesource.com/node_{{ nodejs.version }} {{ ansible_distribution_release }} main'
    state: present
  with_items:
    - deb
    - deb-src

- name: Install nodejs
  apt:
    name: nodejs
    state: present
